spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.1.5:1521:system
    username: "yes"
    password: "1234"
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
      
server:
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  config-location: classpath:mybatis-config.xml