spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "type encrypted url"
    username: "type encrypted username"
    password: "type encrypted password"
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
      
server:
  port : 9080
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  config-location: classpath:mybatis-config.xml